### ISSUE TITLE
Ajustar tamanho dos ícones

### ISSUE THREAD

**Issue by enriquesouza** [aizzy-ai/aizzy#9]
Deixar os ícones dos assistentes do mesmo tamanho dos da home.

Correto
<img width="432" alt="image" src="https://github.com/aizzy-ai/aizzy/assets/1700699/08e6e018-12c5-4526-9b09-971a7fc43cff">

Correto
<img width="72" alt="image" src="https://github.com/aizzy-ai/aizzy/assets/1700699/a062e68e-63f9-4632-8703-67c4d97f276d">

Tamanho errado:

<img width="941" alt="image" src="https://github.com/aizzy-ai/aizzy/assets/1700699/d23df9e7-1bd3-4b10-be12-56697d65623f">

Verificar os icones dentro do botão e também o botao em si.

Verificar padding dentro e fora do botão.

ajustar o campo de busca

<img width="430" alt="image" src="https://github.com/aizzy-ai/aizzy/assets/1700699/5956cacd-89f3-456b-84b4-cc12c1ba742e">

---

### Modelo de Relatório Diário

---

**Relatório Diário**

**Data:** [Insira a data aqui]

**Nome do Funcionário:** [Nome do funcionário]

**Hoje:**

---

#### Nome: [Nome da Tarefa]

**1. Entendimento da Tarefa:**

- [x] Entender a tarefa
- [x] Anotar a tarefa
- [x] Pesquisar a melhor forma de fazer a tarefa
- [x] Entender o motivo pelo qual está fazendo essa tarefa

**2. Implementação:**

- [x] Desenvolver a tarefa

**3. Testes da Tarefa:**

- [x] Testar a margem
- [x] Testar a fonte
- [x] Testar o padding
- [x] Testar a cor
- [x] Testar o clique (se aplicável)
- [x] Testar a responsividade
- [x] Testar a funcionalidade em diferentes navegadores
- [x] Testar a tarefa em dispositivos móveis
- [x] Testar o desempenho (tempo de carregamento, etc.)
- [x] Testar a acessibilidade
- [ ] Outros testes específicos da tarefa (descrever aqui)

**4. Commit e Verificação Final:**

- [x] Commitar o código
- [x] Testar o sistema como um todo
- [x] Prencher planilha de testes do sistema https://docs.google.com/spreadsheets/d/1cFk35zd7TAngN62qad90W4naTBzcP7QEpMMW2N9G8bQ/edit?gid=0#gid=0

- [x] Preencher a planilha de testes com os resultados OK pelo dia
- [x] Subir no ambiente de testes somente se tudo estiver verde

---

### Observações Adicionais

[Espaço para observações adicionais sobre o progresso ou dificuldades encontradas]

---

### Modelo de Planilha de Testes

Abaixo está um modelo de planilha que pode ser preenchido diariamente para registrar os resultados dos testes:

| Data       | Tarefa        | Teste de Margem | Teste de Fonte | Teste de Padding | Teste de Cor | Teste de Clique | Teste de Responsividade | Teste em Diferentes Navegadores | Teste em Dispositivos Móveis | Teste de Desempenho | Teste de Acessibilidade | Outros Testes Específicos | Resultado Final | Comentários          |
|------------|---------------|-----------------|----------------|------------------|--------------|-----------------|-------------------------|-------------------------------|-----------------------------|---------------------|------------------------|---------------------------|----------------|-----------------------|
| [Data]     | [Nome Tarefa] | [OK/Erro]       | [OK/Erro]      | [OK/Erro]        | [OK/Erro]    | [OK/Erro]       | [OK/Erro]               | [OK/Erro]                     | [OK/Erro]                   | [OK/Erro]           | [OK/Erro]               | [Descrever]               | [Aprovado/Não] | [Comentários]         |

---

**Comment by Wendson-Alves** [comment]
Em uma chamada, eu, Luca, e o Gabigol concordamos que os botões dos menus ficariam mais bonitos e organizados se fossem um pouco menores. Portanto, padronizei todos com 36px.
Se tiver ok pra você.
